PROG4HF/Web/Models/Ingatlan.cs
// <copyright file="Ingatlan.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Threading.Tasks;

    /// <summary>
    /// Ingatlan Type: Form Model / MVC Model.
    /// </summary>
    public class Ingatlan
    {
        /// <summary>
        /// Gets or sets id of the ingatlan.
        /// </summary>
        [Display(Name = "Ingatlan Id")]
        public decimal Id { get; set; }

        /// <summary>
        /// Gets or sets type of ingatlan.
        /// </summary>
        [Display(Name = "Ingatlan Típus")]
        [Required]
        public string Type { get; set; }

        /// <summary>
        /// Gets or sets manager of ingatlan.
        /// </summary>
        [Display(Name = "Menedzser")]
        [Required]
        public string Manager { get; set; }

        /// <summary>
        /// Gets or sets district of ingatlan's location.
        /// </summary>
        [Display(Name = "Kerület")]
        [Required]
        public decimal District { get; set; }

        /// <summary>
        /// Gets or sets value is furnished.
        /// </summary>
        [Display(Name = "Bútorozott")]
        public decimal IsFurnished { get; set; }

        /// <summary>
        /// Gets or sets renting fee of ingatlan.
        /// </summary>
        [Display(Name = "Bérleti Díj")]
        [Required]
        public decimal RentFee { get; set; }

        /// <summary>
        /// Gets or sets square meter of ingatlan.
        /// </summary>
        [Display(Name = "Négyzetméter")]
        [Required]
        public decimal SqrMeter { get; set; }
    }
}

PROG4HF/Web/Controllers/IngatlansController.cs
// <copyright file="IngatlansController.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Globalization;
    using System.Linq;
    using System.Threading.Tasks;
    using AutoMapper;
    using Logicc;
    using Microsoft.AspNetCore.Mvc;
    using Web.Models;

    /// <summary>
    /// Controller.
    /// </summary>
    public class IngatlansController : Controller
    {
        private ILogic logic;
        private IMapper mapper;
        private IngatlanListViewModel vm;

        /// <summary>
        /// Initializes a new instance of the <see cref="IngatlansController"/> class.
        /// </summary>
        /// <param name="logic">Ilogic.</param>
        /// <param name="mapper">IMapper.</param>
        public IngatlansController(ILogic logic, IMapper mapper)
        {
            this.logic = logic;
            this.mapper = mapper;

            this.vm = new IngatlanListViewModel();
            this.vm.EditedIngatlan = new Models.Ingatlan();
            var ingatlanok = this.logic.ReadIngatlan();
            this.vm.GetIngatlans = new Collection<Ingatlan>();
            foreach (var item in ingatlanok)
            {
                if (mapper is not null)
                {
                    this.vm.GetIngatlans.Add(mapper.Map<Data.Models.Ingatlanok, Ingatlan>(item));
                }
            }
        }

        /// <summary>
        /// Index action.
        /// </summary>
        /// <returns>view.</returns>
        public IActionResult Index()
        {
            this.ViewData["editAction"] = "AddNew";
            return this.View("IngatlanIndex", this.vm);
        }

        /// <summary>
        /// Details action.
        /// </summary>
        /// <returns>view.</returns>
        /// <param name="id">ID.</param>
        public IActionResult Details(int id)
        {
            return this.View("IngatlansDetails", this.GetIngatlanModel(id));
        }

        /// <summary>
        /// Remove action.
        /// </summary>
        /// <returns>view.</returns>
        /// <param name="id">ID.</param>
        public IActionResult Remove(int id)
        {
            string i = id.ToString(CultureInfo.CurrentCulture);
            this.logic.DeleteIngatlan(i);
            this.TempData["editResult"] = "Delete OK";
            return this.RedirectToAction(nameof(this.Index));
        }

        /// <summary>
        /// Edit action.
        /// </summary>
        /// <returns>view.</returns>
        /// <param name="id">ID.</param>
        public IActionResult Edit(int id)
        {
            this.ViewData["editAction"] = "Edit";
            this.vm.EditedIngatlan = this.GetIngatlanModel(id);
            return this.View("IngatlanIndex", this.vm);
        }

        /// <summary>
        /// Edit.
        /// </summary>
        /// <param name="ingatlan">Ingatlan Entity.</param>
        /// <param name="editAction">Action.</param>
        /// <returns>View.</returns>
        [HttpPost]
        public IActionResult Edit(Models.Ingatlan ingatlan, string editAction)
        {
            if (this.ModelState.IsValid && ingatlan != null)
            {
                this.TempData["editResult"] = "Edit OK";
                if (editAction == "AddNew")
                {
                    Data.Models.Ingatlanok ing = new Data.Models.Ingatlanok();
                    ing.BerletiDij = ingatlan.RentFee;
                    ing.Butorozott = ingatlan.IsFurnished;
                    ing.Kerulet = ingatlan.District;
                    ing.Menedzser = ingatlan.Manager;
                    ing.Negyzetmeter = ingatlan.SqrMeter;
                    ing.Tipus = ingatlan.Type;
                    this.logic.CreateIngatlan(ing);
                }
                else
                {
                    this.logic.UpdateIngatlan(ingatlan.Id.ToString(CultureInfo.CurrentCulture), "Menedzser", ingatlan.Manager);
                    this.logic.UpdateIngatlan(ingatlan.Id.ToString(CultureInfo.CurrentCulture), "BerletiDij", ingatlan.RentFee.ToString(CultureInfo.CurrentCulture));
                }

                return this.RedirectToAction(nameof(this.Index));
            }
            else
            {
                this.ViewData["editAction"] = "Edit";
                this.vm.EditedIngatlan = ingatlan;
                return this.View("IngatlanIndex", this.vm);
            }
        }

        private Models.Ingatlan GetIngatlanModel(int id)
        {
            Data.Models.Ingatlanok ing = this.logic.GetOneIngatlan(id);
            return this.mapper.Map<Data.Models.Ingatlanok, Models.Ingatlan>(ing);
        }
    }
}

PROG4HF/Web/Views/Ingatlans/IngatlanIndex.cshtml
@model Web.Models.IngatlanListViewModel

@{
    ViewData["Title"] = "IngatlanIndex";
}

<h2>Ingatlan Főoldal</h2>

<p style="color:red">@TempData["editResult"]</p>

@await Html.PartialAsync("IngatlansEdit", Model.EditedIngatlan)

@await Html.PartialAsync("IngatlansList", Model.GetIngatlans)

PROG4HF/Web/Views/Ingatlans/IngatlansDetails.cshtml
@model Web.Models.Ingatlan

@{
    ViewData["Title"] = "IngatlansDetails";
}

<h2>Ingatlan adatok</h2>

@Html.ActionLink("Back to the list", "Index");

<table border="1">
    <tr>
        <td>@Html.DisplayNameFor(m => m.Type)</td>
        <td>@Html.DisplayFor(m => m.Type)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.SqrMeter)</td>
        <td>@Html.DisplayFor(m => m.SqrMeter)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.RentFee)</td>
        <td>@Html.DisplayFor(m => m.RentFee)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.District)</td>
        <td>@Html.DisplayFor(m => m.District)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.IsFurnished)</td>
        <td>@Html.DisplayFor(m => m.IsFurnished)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Manager)</td>
        <td>@Html.DisplayFor(m => m.Manager)</td>
    </tr>
</table>

PROG4HF/Web/Views/Ingatlans/IngatlansEdit.cshtml
@model Web.Models.Ingatlan

<h2>Ingatlan módosító</h2>

@using (Html.BeginForm("Edit", "Ingatlans"))
{
    @Html.ValidationSummary()
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.Id)
    @Html.Hidden("editAction", ViewData["editAction"].ToString())

    <div class="editor-label">@Html.LabelFor(m => m.Manager)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Manager)</div>

    <div class="editor-label">@Html.LabelFor(m => m.RentFee)</div>
    <div class="editor-field">@Html.EditorFor(m => m.RentFee)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Type)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Type)</div>
    
    <div class="editor-label">@Html.LabelFor(m => m.District)</div>
    <div class="editor-field">@Html.EditorFor(m => m.District)</div>
    
    <div class="editor-label">@Html.LabelFor(m => m.SqrMeter)</div>
    <div class="editor-field">@Html.EditorFor(m => m.SqrMeter)</div>
    
    <input type="submit" value="SEND" />
}

PROG4HF/Web/Views/Ingatlans/IngatlansList.cshtml
@model IEnumerable<Web.Models.Ingatlan>

<h2>Ingatlanok Listája</h2>

@if (Model.Count() == 0)
{
    <p>Nincs ingatlan az adatbázisban.</p>
}
else
{
    <table border="1">
        <tr>
            <th>@Html.DisplayNameFor(m => m.First().Type)</th>
            <th>@Html.DisplayNameFor(m => m.First().RentFee)</th>
            <th>Adatlap</th>
            <th>Törlés</th>
            <th>Módosítás</th>
        </tr>
        @foreach (var ingatlan in Model)
        {
    <tr>
        <td>@Html.DisplayFor(m => ingatlan.Type)</td>
        <td>@Html.DisplayFor(m => ingatlan.RentFee)</td>
        <td>@Html.ActionLink("[SHOW]", "Details", new { id = ingatlan.Id })</td>
        <td>@Html.ActionLink("[DEL]", "Remove", new { id = ingatlan.Id })</td>
        <td>@Html.ActionLink("[EDIT]", "Edit", new { id = ingatlan.Id })</td>
    </tr>
        }
        </table>
}